events {}

http {
    server {
        listen 80;

        location /downloads/ {
            alias /usr/share/nginx/html/downloads/;

            # SECURE LINK TEMPORARILY DISABLED FOR DEBUGGING
            # Re-enable after pipeline is confirmed working end-to-end
            add_header Accept-Ranges bytes;
        }
    }
}
